# Generated by Django 5.0.6 on 2024-07-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planet',
        ),
    ]
