# Generated by Django 5.0.6 on 2024-07-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetdb',
            name='planet_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='planetdb',
            name='planet_position',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='planetdb',
            name='planet_temperature',
            field=models.SmallIntegerField(default=0, verbose_name='Temperature'),
        ),
    ]
