# Generated by Django 5.0.6 on 2024-07-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0002_alter_planetdb_planet_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountusersettingdb',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelTable(
            name='accountusersettingdb',
            table='Accounts Manager',
        ),
    ]
