# Generated by Django 5.0.6 on 2024-07-09 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0007_alter_accountusersettingdb_account_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountusersettingdb',
            name='account_class',
            field=models.CharField(blank=True, choices=[('G', 'General'), ('D', 'Discoverer'), ('M', 'Merchant')], max_length=1, null=True, verbose_name='Account Class'),
        ),
        migrations.AlterField(
            model_name='accountusersettingdb',
            name='universe_economy',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Economy Speed'),
        ),
        migrations.AlterField(
            model_name='accountusersettingdb',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
    ]
