# Generated by Django 5.0.6 on 2024-07-10 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0008_alter_accountusersettingdb_account_class_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountTechnologiesDb',
        ),
    ]
