# Generated by Django 5.0.6 on 2024-07-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0009_delete_accounttechnologiesdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceBuildingDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50, verbose_name='Building Name')),
                ('building_level', models.PositiveSmallIntegerField(default=0, max_length=3, verbose_name='Building Level')),
                ('planet_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empire.planetdb', verbose_name='Planet Name')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'db_table': 'Resource Buildings Table',
            },
        ),
    ]
