# Generated by Django 5.0.6 on 2024-07-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0010_resourcebuildingdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebuildingdb',
            name='building_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Building Level'),
        ),
    ]
