# Generated by Django 5.0.6 on 2024-07-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0011_alter_resourcebuildingdb_building_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebuildingdb',
            name='building_level',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='resourcebuildingdb',
            name='building_name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
