# Generated by Django 5.0.6 on 2024-07-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0012_alter_resourcebuildingdb_building_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetdb',
            name='planet_name',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
