# Generated by Django 5.0.6 on 2024-07-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0014_alter_accountusersettingdb_user_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planetdb',
            name='account_fk',
        ),
        migrations.RemoveField(
            model_name='resourcebuildingdb',
            name='planet_fk',
        ),
        migrations.DeleteModel(
            name='AccountUserSettingDb',
        ),
        migrations.DeleteModel(
            name='PlanetDb',
        ),
        migrations.DeleteModel(
            name='ResourceBuildingDb',
        ),
    ]
