# Generated by Django 5.0.6 on 2024-07-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0016_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('temperature', models.SmallIntegerField(default=0)),
                ('life_form_type', models.CharField(choices=[('H', 'Human'), ('K', 'Kaelesh'), ('M', 'Mecha'), ('R', 'Rock_Tal')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='GameProfile',
        ),
    ]
