# Generated by Django 5.0.6 on 2024-07-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='universe_speed',
            field=models.SmallIntegerField(default=1),
        ),
    ]
