# Generated by Django 5.0.6 on 2024-07-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0019_profile_universe_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empire.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empire.planet')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Armor Technology'), ('2', 'Intergalactic Technology'), ('3', 'Plasma Technology')])),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empire.profile')),
            ],
        ),
    ]
