# Generated by Django 5.0.6 on 2024-07-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0021_alter_technology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(choices=[('1', 'Armor Technology'), ('2', 'Intergalactic Technology'), ('3', 'Plasma Technology')]),
        ),
    ]
