# Generated by Django 5.0.6 on 2024-07-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0023_building_user_planet_user_technology_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='user',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='user',
        ),
    ]
